#!usr/bin/env sh

f="$(git diff --name-only --cached --diff-filter=ACMR -- "*.cpp" "*.hpp")"

if ! [ -z "$f" ]; then
  echo "==> Running formatter"
  clang-format -i $f
else
  echo "No files to format"
fi
